name: cd

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:

  packagist-deploy:
    name: "Packagist deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Packagist Sync
        uses: hotaruma/packagist-sync@v1.0.0
        with:
          api-token: ${{ secrets.packagist_token }}

  upload-coverage-report:
    name: "Upload coverage results"
    runs-on: ubuntu-latest

    steps:

      - uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - uses: codecov/codecov-action@v3
        id: download-codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: clover.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true

      - name: Download path
        run: echo ${{steps.download-codecov.outputs.download-path}}
